"""meaningful message

Revision ID: 4ef2c02d8d63
Revises: 88be68dfa959
Create Date: 2023-08-23 19:19:55.556443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef2c02d8d63'
down_revision = '88be68dfa959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images_table', schema=None) as batch_op:
        batch_op.drop_column('image_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
