"""add userphoto and session date

Revision ID: 4f0cc3a96d44
Revises: 282991327db9
Create Date: 2023-08-25 09:36:27.046571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0cc3a96d44'
down_revision = '282991327db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_sessions_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_date', sa.String(), nullable=True))

    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_column('user_image')

    with op.batch_alter_table('photo_sessions_table', schema=None) as batch_op:
        batch_op.drop_column('session_date')

    # ### end Alembic commands ###
