"""add userphoto and session date

Revision ID: 98ee0a4df634
Revises: 4f0cc3a96d44
Create Date: 2023-08-25 10:00:10.142256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ee0a4df634'
down_revision = '4f0cc3a96d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_bio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_column('user_bio')

    # ### end Alembic commands ###
