"""add userphoto and session date

Revision ID: ad701714f3ac
Revises: 98ee0a4df634
Create Date: 2023-08-25 10:02:29.358760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad701714f3ac'
down_revision = '98ee0a4df634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_sessions_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_request', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_sessions_table', schema=None) as batch_op:
        batch_op.drop_column('session_request')

    # ### end Alembic commands ###
