"""message

Revision ID: ff32085d3caf
Revises: 
Create Date: 2023-09-01 09:36:31.064868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff32085d3caf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_title', sa.String(), nullable=True),
    sa.Column('set_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_set_table'))
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('user_role', sa.String(), nullable=False),
    sa.Column('user_image', sa.String(), nullable=True),
    sa.Column('user_bio', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_table')),
    sa.UniqueConstraint('username', name=op.f('uq_users_table_username'))
    )
    op.create_table('dogs_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_name', sa.String(), nullable=True),
    sa.Column('dog_breed', sa.String(), nullable=True),
    sa.Column('dog_age', sa.Integer(), nullable=True),
    sa.Column('dog_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_owner_id'], ['users_table.id'], name=op.f('fk_dogs_table_dog_owner_id_users_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dogs_table'))
    )
    op.create_table('images_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('image_liked_by_users', sa.String(), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['set_table.id'], name=op.f('fk_images_table_set_id_set_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images_table'))
    )
    op.create_table('photo_sessions_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_price', sa.Integer(), nullable=True),
    sa.Column('session_description', sa.String(), nullable=True),
    sa.Column('session_request', sa.String(), nullable=True),
    sa.Column('session_date', sa.String(), nullable=True),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('photographer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs_table.id'], name=op.f('fk_photo_sessions_table_dog_id_dogs_table')),
    sa.ForeignKeyConstraint(['photographer_id'], ['users_table.id'], name=op.f('fk_photo_sessions_table_photographer_id_users_table')),
    sa.ForeignKeyConstraint(['set_id'], ['set_table.id'], name=op.f('fk_photo_sessions_table_set_id_set_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo_sessions_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_sessions_table')
    op.drop_table('images_table')
    op.drop_table('dogs_table')
    op.drop_table('users_table')
    op.drop_table('set_table')
    # ### end Alembic commands ###
